import { StyleSheet } from 'react-native';

export const dashboardStyles = StyleSheet.create({
    page: {
        flex: 1,
        backgroundColor: '#f3f4f6',
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingBottom: 16,
        paddingHorizontal: 16,
    },
    avatar: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#2e539e',
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 12,
    },
    avatarText: { color: '#fff', fontWeight: '700' },
    greetingLabel: { color: '#060606ff', fontSize: 12 },
    greetingName: { color: '#060606ff', fontWeight: '700' },
    refreshBtn: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#fff',
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#000',
        shadowOpacity: 0.06,
        shadowRadius: 6,
        shadowOffset: { width: 0, height: 2 },
        elevation: 1,
    },

    summaryCard: {
        flexDirection: 'row',
        backgroundColor: '#fff',
        borderRadius: 16,
        paddingVertical: 20,
        paddingHorizontal: 24,
        marginHorizontal: 16,
        marginTop: 8,
        marginBottom: 20,
        shadowColor: '#000',
        shadowOpacity: 0.08,
        shadowRadius: 12,
        shadowOffset: { width: 0, height: 6 },
        elevation: 2,
    },
    summaryItem: { flex: 1, alignItems: 'center' },
    summaryValue: { fontSize: 24, fontWeight: '700', color: '#111827' },
    summaryLabel: { color: '#6b7280', marginTop: 4 },
    separator: { width: 1, backgroundColor: '#e5e7eb', marginHorizontal: 12 },

    // New summary card styles for side-by-side layout
    summaryRow: {
        flexDirection: 'row',
        marginHorizontal: 16,
        marginTop: 8,
        marginBottom: 20,
        gap: 12,
    },
    summaryCardSmall: {
        flex: 1,
        backgroundColor: '#fff',
        borderRadius: 16,
        padding: 16,
        shadowColor: '#000',
        shadowOpacity: 0.08,
        shadowRadius: 12,
        shadowOffset: { width: 0, height: 6 },
        elevation: 2,
        alignItems: 'center',
    },
    summaryIconWrapper: {
        width: 48,
        height: 48,
        borderRadius: 24,
        backgroundColor: '#dbeafe',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 12,
    },
    summaryValueSmall: {
        fontSize: 28,
        fontWeight: '700',
        color: '#111827',
        marginBottom: 4,
    },
    summaryLabelSmall: {
        fontSize: 13,
        color: '#6b7280',
        fontWeight: '600',
        marginBottom: 8,
    },
    subStatsRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 4,
    },
    subStat: {
        flex: 1,
        alignItems: 'center',
    },
    subStatValue: {
        fontSize: 16,
        fontWeight: '700',
    },
    subStatLabel: {
        fontSize: 10,
        color: '#9ca3af',
        marginTop: 2,
    },
    subStatDivider: {
        width: 1,
        height: 20,
        backgroundColor: '#e5e7eb',
        marginHorizontal: 8,
    },
    draftSubtext: {
        fontSize: 11,
        color: '#9ca3af',
        marginTop: 4,
    },

    statusRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginHorizontal: 16,
        marginBottom: 12,
        gap: 8,
    },
    statusText: { color: '#6b7280', fontSize: 13 },
    retryText: { color: '#1f3a8a', fontWeight: '600', fontSize: 13 },

    sectionTitle: { color: '#17336d', fontWeight: '700', marginBottom: 12, fontSize: 16, marginHorizontal: 16 },

    card: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#fff',
        borderRadius: 16,
        padding: 14,
        marginBottom: 12,
        marginHorizontal: 16,
        shadowColor: '#000',
        shadowOpacity: 0.08,
        shadowRadius: 12,
        shadowOffset: { width: 0, height: 6 },
        elevation: 2,
    },
    iconBadge: {
        width: 36,
        height: 36,
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 12,
        borderWidth: 1,
    },
    cardTitle: { fontWeight: '600', color: '#1f2937' },
    cardSubtitle: { color: '#6b7280', fontSize: 12 },
    cardValue: { fontWeight: '700', color: '#111827', fontSize: 18 },

    seeReportsBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#1f3a8a',
        borderRadius: 14,
        paddingVertical: 14,
        paddingHorizontal: 20,
        shadowColor: '#1f3a8a',
        shadowOpacity: 0.18,
        shadowRadius: 10,
        shadowOffset: { width: 0, height: 6 },
    },
    seeReportsBtnText: { color: '#fff', fontWeight: '700', fontSize: 15 },
    seeDraftsBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#fff',
        borderRadius: 14,
        paddingVertical: 14,
        paddingHorizontal: 20,
        borderWidth: 1.5,
        borderColor: '#1f3a8a',
        shadowColor: '#000',
        shadowOpacity: 0.05,
        shadowRadius: 8,
        shadowOffset: { width: 0, height: 2 },
    },
    seeDraftsBtnText: { color: '#1f3a8a', fontWeight: '700', fontSize: 15 },
    unsyncedBadge: {
        backgroundColor: '#ef4444',
        borderRadius: 10,
        paddingHorizontal: 7,
        paddingVertical: 2,
        marginLeft: 8,
        minWidth: 22,
        alignItems: 'center',
    },
    unsyncedBadgeText: { color: '#fff', fontWeight: '700', fontSize: 11 },

    // Empty state styles
    emptyState: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 40,
        marginHorizontal: 16,
        backgroundColor: '#fff',
        borderRadius: 16,
        shadowColor: '#000',
        shadowOpacity: 0.08,
        shadowRadius: 12,
        shadowOffset: { width: 0, height: 6 },
        elevation: 2,
    },
    emptyStateText: {
        fontSize: 16,
        fontWeight: '600',
        color: '#374151',
        marginTop: 12,
    },
    emptyStateSubtext: {
        fontSize: 13,
        color: '#9ca3af',
        marginTop: 4,
    },

    // Activity card styles
    activityCard: {
        backgroundColor: '#fff',
        borderRadius: 16,
        padding: 16,
        marginBottom: 12,
        marginHorizontal: 16,
        shadowColor: '#000',
        shadowOpacity: 0.08,
        shadowRadius: 12,
        shadowOffset: { width: 0, height: 6 },
        elevation: 2,
    },
    activityHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 12,
    },
    activityIcon: {
        width: 40,
        height: 40,
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 12,
        borderWidth: 1.5,
    },
    activityTitle: {
        fontSize: 15,
        fontWeight: '600',
        color: '#111827',
    },
    activitySubtitle: {
        fontSize: 12,
        color: '#6b7280',
        marginTop: 2,
    },
    statusBadge: {
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 8,
    },
    statusBadgeText: {
        fontSize: 11,
        fontWeight: '600',
    },
    activityDetails: {
        gap: 6,
    },
    activityDetailRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    activityDetailText: {
        fontSize: 13,
        color: '#6b7280',
        flex: 1,
    },
});