import { StyleSheet } from 'react-native';

export const leakReportFormStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#f5f5f9' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#e2e8f0',
  },
  closeBtn: { padding: 4 },
  headerTitle: { fontSize: 18, fontWeight: '600', color: '#334155' },
  scroll: { flex: 1 },
  scrollContent: { padding: 16 },

  infoCard: {
    backgroundColor: '#fff',
    padding: 14,
    borderRadius: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  infoHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 8 },
  infoHeaderText: { fontSize: 14, fontWeight: '600', color: '#10b981' },
  infoRow: { flexDirection: 'row', marginBottom: 8, gap: 12 },
  infoLabel: { fontSize: 12, color: '#6b7280', marginBottom: 2 },
  infoValue: { fontSize: 14, color: '#111', fontWeight: '600' },
  coordsText: { fontSize: 12, color: '#6b7280', marginTop: 4, lineHeight: 16 },

  // Leak Location styles
  leakLocationCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 14,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#fecaca',
    borderLeftWidth: 4,
    borderLeftColor: '#dc2626',
  },
  leakLocationHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  leakLocationTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: '#dc2626',
  },
  leakLocationSet: {
    backgroundColor: '#fef2f2',
    borderRadius: 8,
    padding: 12,
  },
  leakCoordsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 4,
  },
  leakCoordsText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#991b1b',
  },
  leakMethodText: {
    fontSize: 12,
    color: '#7f1d1d',
    marginBottom: 8,
  },
  clearLeakLocationBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: '#fecaca',
  },
  clearLeakLocationText: {
    fontSize: 12,
    color: '#dc2626',
    fontWeight: '500',
  },
  leakLocationOptions: {
    gap: 10,
  },
  leakLocationHint: {
    fontSize: 13,
    color: '#6b7280',
    marginBottom: 4,
  },
  leakLocationButtons: {
    flexDirection: 'row',
    gap: 10,
  },
  leakLocationBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#dc2626',
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 8,
    gap: 6,
  },
  leakLocationBtnSecondary: {
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#1e5a8e',
  },
  leakLocationBtnText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#fff',
  },
  leakLocationNote: {
    fontSize: 12,
    color: '#9ca3af',
    textAlign: 'center',
    marginTop: 4,
  },

  instructionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#e6f0fb',
    padding: 10,
    borderRadius: 8,
    marginBottom: 16,
  },
  instructionText: { fontSize: 13, color: '#1e5a8e', fontWeight: '500' },

  sectionLabel: { fontSize: 14, color: '#6b7280', marginBottom: 10, fontWeight: '500' },

  buttonGrid: { flexDirection: 'row', marginBottom: 10, gap: 10 },
  choiceBtn: {
    flex: 1,
    backgroundColor: '#fff',
    paddingVertical: 14,
    borderRadius: 10,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  choiceBtnActive: {
    backgroundColor: '#1e5a8e',
    borderColor: '#1e5a8e',
  },
  choiceBtnText: { color: '#334155', fontWeight: '600' },
  choiceBtnTextActive: { color: '#fff' },

  inputWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 10,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  input: { flex: 1, fontSize: 15, color: '#111' },

  photoSection: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#e6f0fb',
    padding: 10,
    borderRadius: 8,
    marginBottom: 12,
  },
  photoSectionText: { fontSize: 13, color: '#1e5a8e', fontWeight: '500' },

  photoHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  photoLabel: { fontSize: 14, color: '#6b7280', fontWeight: '500' },
  photoCount: { fontSize: 13, color: '#9aa5b1' },

  photoGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginBottom: 16,
  },
  photoBtn: {
    backgroundColor: '#fff',
    width: 100,
    height: 100,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#e2e8f0',
    borderStyle: 'dashed',
    alignItems: 'center',
    justifyContent: 'center',
  },
  photoBtnLabel: { fontSize: 18, color: '#1e5a8e', fontWeight: '600', marginTop: 4 },
  photoPreview: {
    width: 100,
    height: 100,
    borderRadius: 12,
    overflow: 'hidden',
    position: 'relative',
  },
  photoImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  photoRemove: {
    position: 'absolute',
    top: 4,
    right: 4,
    backgroundColor: '#fff',
    borderRadius: 12,
  },

  footerNote: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  footerNoteText: { fontSize: 12, color: '#6b7280' },

  buttonRow: {
    flexDirection: 'row',
    gap: 12,
  },
  saveDraftBtn: {
    flex: 1,
    backgroundColor: '#fff',
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    borderWidth: 2,
    borderColor: '#3b82f6',
  },
  saveDraftBtnText: {
    color: '#3b82f6',
    fontSize: 14,
    fontWeight: '700',
    marginLeft: 6,
  },
  sendBtn: {
    flex: 2,
    backgroundColor: '#1e5a8e',
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  sendBtnOffline: {
    backgroundColor: '#6366f1',
  },
  sendBtnText: { color: '#fff', fontSize: 16, fontWeight: '700', letterSpacing: 0.5 },
  radioGroup: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 12 },
  radioGroupSmall: { flexDirection: 'row', gap: 20, marginBottom: 12 },
  radioRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  radioCircle: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#1e5a8e',
    backgroundColor: '#fff',
  },
  radioCircleActive: { backgroundColor: '#1e5a8e' },
  radioLabel: { marginLeft: 6, fontSize: 14, color: '#334155', fontWeight: '600' },
  radioList: { backgroundColor: '#fff', borderWidth: 1, borderColor: '#e2e8f0', borderRadius: 8, padding: 10, marginBottom: 12 },
  radioListRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 8 },
  radioListLabel: { marginLeft: 10, fontSize: 14, color: '#334155' },
  
  collapseHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#fff',
    padding: 14,
    borderRadius: 10,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  collapseHeaderLeft: {
    flex: 1,
  },
  selectedValue: {
    fontSize: 13,
    color: '#1e5a8e',
    fontWeight: '600',
    marginTop: 4,
  },
  
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.4)', justifyContent: 'center', padding: 20 },
  modalCard: { backgroundColor: '#fff', borderRadius: 12, padding: 16, maxHeight: '80%' },
  modalTitle: { fontSize: 16, fontWeight: '700', marginBottom: 12, color: '#1e3a5f' },
  dmaItem: { paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: '#eef2f7' },
  dmaText: { fontSize: 14, color: '#334155' },
  modalCancel: { alignItems: 'center', paddingVertical: 12 },
  modalCancelText: { color: '#1e5a8e', fontWeight: '700' },
  
  // Preview Modal Styles
  previewOverlay: { 
    flex: 1, 
    backgroundColor: 'rgba(0,0,0,0.5)', 
    justifyContent: 'flex-end',
  },
  previewCard: { 
    backgroundColor: '#fff', 
    borderTopLeftRadius: 24, 
    borderTopRightRadius: 24,
    maxHeight: '90%',
    paddingBottom: 20,
  },
  previewHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#e2e8f0',
  },
  previewTitle: {
    flex: 1,
    fontSize: 18,
    fontWeight: '700',
    color: '#1e3a5f',
    marginLeft: 10,
  },
  previewCloseBtn: {
    padding: 4,
  },
  previewScroll: {
    maxHeight: 400,
    paddingHorizontal: 16,
  },
  previewSection: {
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  previewSectionTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1e5a8e',
    marginBottom: 10,
    textTransform: 'uppercase',
  },
  previewRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    paddingVertical: 6,
  },
  previewLabel: {
    fontSize: 14,
    color: '#6b7280',
    flex: 1,
  },
  previewValue: {
    fontSize: 14,
    color: '#111',
    fontWeight: '600',
    flex: 1.5,
    textAlign: 'right',
  },
  previewPhotoRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 8,
    marginBottom: 8,
  },
  previewPhoto: {
    width: 60,
    height: 60,
    borderRadius: 8,
  },
  previewActions: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    paddingTop: 16,
    gap: 12,
  },
  previewCancelBtn: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
    backgroundColor: '#f1f5f9',
  },
  previewCancelText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#475569',
  },
  previewConfirmBtn: {
    flex: 1.5,
    flexDirection: 'row',
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#10b981',
  },
  previewConfirmText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#fff',
  },
});

export default leakReportFormStyles;
